##
## OCIO
##

build_component(
 NAME OCIO
 VERSION "v1.1.1"
 URL "https://github.com/AcademySoftwareFoundation/OpenColorIO"
 BUILD_ARGS
 "-DCMAKE_CXX_FLAGS:STRING=-fPIC -w"
 -DOCIO_BUILD_TRUELIGHT=OFF
 -DOCIO_BUILD_APPS=OFF
 -DOCIO_BUILD_NUKE=OFF
 -DOCIO_BUILD_DOCS=OFF
 -DOCIO_BUILD_TESTS=OFF
 -DOCIO_BUILD_PYGLUE=OFF
 -DOCIO_BUILD_JNIGLUE=OFF
 -DOCIO_STATIC_JNIGLUE=OFF
 -DOCIO_BUILD_STATIC=OFF
 -DOCIO_BUILD_SHARED=ON
 -DYAML_CPP_OBJECT_LIB_EMBEDDED=ON
 -DTINYXML_OBJECT_LIB_EMBEDDED=ON
 DEPENDS_ON OpenEXR OIIO
)