##
## OpenVDB
##

set(OpenVDB_ARGS
    -DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}
    -DBoost_NO_SYSTEM_PATHS=ON
    -DBoost_NO_BOOST_CMAKE=ON
    -DUSE_PKGCONFIG=OFF
    -DOPENVDB_BUILD_DOCS=OFF
    -DOPENVDB_BUILD_PYTHON_MODULE=OFF
    -DOPENVDB_BUILD_UNITTESTS=OFF
    -DIlmBase_ROOT=${CMAKE_INSTALL_PREFIX}
    -DCONCURRENT_MALLOC=None
)

set(OpenVDB_DEPENDENCIES boost)

if(BUILD_TBB)
    set(OpenVDB_ARGS
        $OpenVDB_ARGS}
        -DTBB_LOCATION=${CMAKE_INSTALL_PREFIX}
    )
    set(OpenVDBDEPENDENCIES
        ${OpenVDB_DEPENDENCIES}
        tbb
    )
endif()

build_component(
  NAME OpenVDB
  VERSION "v8.0.0"
  URL https://github.com/AcademySoftwareFoundation/openvdb
  BUILD_ARGS ${OpenVDB_ARGS}
  DEPENDS_ON ${OpenVDB_DEPENDENCIES}
)