##
## OIIO
##

build_component(
 NAME OIIO
 VERSION "Release-1.8.17"
 URL "https://github.com/OpenImageIO/oiio"
 BUILD_ARGS
  -DBOOST_ROOT=${CMAKE_INSTALL_PREFIX} 
  -DBoost_NO_SYSTEM_PATHS=ON 
  -DBoost_NO_BOOST_CMAKE=ON 
  -DOIIO_BUILD_TOOLS=ON
  -DOIIO_BUILD_TESTS=OFF
  -DUSE_PYTHON=OFF
  -DSTOP_ON_WARNING=OFF
  #-DOPENEXR_ROOT_DIR=${CMAKE_INSTALL_PREFIX}  # for OIIO > 1.8
  -DOPENEXR_HOME=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=On
  -DUSE_PTEX=OFF
 DEPENDS_ON OpenEXR ${EP_BOOST}
)